In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

### 1. Загрузка данных

In [2]:
df = pd.read_csv('data/bank/bank-full.csv', sep=';')

print(f"Размер исходного датасета: {df.shape}")
df.head(3)

Размер исходного датасета: (45211, 17)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no

### 2. Обработка данных

In [3]:
bins = [0, 25, 60, 120]
labels = ['young', 'adult', 'senior']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)
df = df.drop(columns=['age'])
df['y'] = df['y'].map({'yes': 1, 'no': 0})

In [4]:
num_cols = ['balance', 'day', 'duration', 'campaign', 'pdays', 'previous']
cat_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'age_group']

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [5]:
df = pd.get_dummies(df, columns=['job', 'marital', 'education', 'default', 'housing', 'loan',
                                  'contact', 'month', 'poutcome', 'age_group'], drop_first=True)

print(f"Итоговое количество столбцов после кодирования: {df.shape[1]}")
display(df.head(3))

Итоговое количество столбцов после кодирования: 44

,balance,day,duration,campaign,pdays,previous,y,job_blue-collar,job_entrepreneur,job_housemaid,...,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_other,poutcome_success,poutcome_unknown,age_group_adult,age_group_senior
0,0.256419,-1.298476,0.011016,-0.569351,-0.411453,-0.25194,0,False,False,False,...,False,True,False,False,False,False,False,True,True,False
1,-0.437895,-1.298476,-0.416127,-0.569351,-0.411453,-0.25194,0,False,False,False,...,False,True,False,False,False,False,False,True,True,False
2,-0.446762,-1.298476,-0.707361,-0.569351,-0.411453,-0.25194,0,False,True,False,...,False,True,False,False,False,False,False,True,True,False

In [6]:
X = df.drop(columns=['y'])
y = df['y']

print("Базовая подготовка данных успешно завершена!")

Базовая подготовка данных успешно завершена!

In [7]:
%store X
%store y

Stored 'X' (DataFrame)
Stored 'y' (Series)